name: Frontend Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - ci/auto-test # For testing the workflow itself

jobs:
  frontend-test:
    name: Frontend SvelteKit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontapp/package-lock.json'

      - name: Install dependencies
        working-directory: ./frontapp
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./frontapp
        run: npx playwright install --with-deps

      - name: Check Formatting & Lint
        working-directory: ./frontapp
        run: npm run lint
        continue-on-error: true

      - name: Run Vitest
        working-directory: ./frontapp
        run: npm run test
        env:
          CI: 'true'

      - name: Run Playwright E2E
        working-directory: ./frontapp
        run: npm run test:e2e
        env:
          CI: 'true'
